name: CI
on: [push]
jobs:
  ci:
    if: "! contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2
      # We need to fetch main so that "lerna run test --since origin/main" works
      # https://github.com/actions/checkout/issues/118
      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install
        run: npm install --ignore-scripts && npm run install:only -- @sidetree/cas-ipfs

      - name: Test
        run: npm run test:only -- @sidetree/cas-ipfs
